---
title: "Research"
---

<!-- ## Peer-reviewed articles -->

<!-- - Delouis, M., & Coauthor, A. (2025). _Placeholder article title goes here._ -->

<!--   *Journal Name*, 00(0), 000–000. -->

<!--   [PDF](#) · [DOI](https://doi.org/PLACEHOLDER) -->

<!-- - Delouis, M. (2024). _Another placeholder article title._ -->

<!--   *Journal Name*, 00(0), 000–000. -->

<!--   [PDF](#) · [DOI](https://doi.org/PLACEHOLDER) -->

## Working papers

-   **Delouis-Jost, M.** (2026). Marching Together? Military Conscription and Immigration Attitudes in Europe. Working paper. [Preprint](https://doi.org/10.21203/rs.3.rs-9242475/v1).

-   **Alrababah, A., Delouis-Jost, M., Gauthier, G & Polak, A.** (2025). Cycling through Elections:The Political Consequences of the Tour de France. Under review at *American Political Science Review*. [Preprint](https://doi.org/10.31235/osf.io/fj4vh_v1).

## Work in progress

-   The Supply Side of Take-Up: Administrative Capacity and the Production of Citizenship in Germany. With **Jorah Diethold, Niklas Harder, and Giuseppe Pietrantuono**. Under review at *American Journal of Political Science*.

-   Army of Unity? Conscription and the Making of Belonging in Reunified Germany. **Solo**-authored.

-   The Costs of Belonging: Military Service and Citizenship Uptake in Sweden and the Netherlands. With **Giuseppe Pietrantuono**.

-   Anti-Muslim Bias and Naturalization In Switzerland. With **Mattia Cecchi**.
